### PR TITLE
Add Prettier for frontend files

### PR DESCRIPTION
**Pull request by TangerineFloof**
Adds and configures Prettier for all frontend files (and frontend-related infrastructure files).

I used the stock Prettier configuration without customization.

There are a lot of changes in the third commit, but they're exclusively the result of running `yarn prettier --write .`. I recommend reviewing the first two commits individually rather than the final PR diff.

The only notable code change was needing to remove a `// @ts-ignore` comment in [**Artisan.ts**](https://github.com/veelkoov/fuzzrake/blob/dbc656af8e73d65fbfc6da857985fc059e6e3898/symfony/assets/scripts/class/Artisan.ts#L183). I needed to do this because Prettier wraps the single line onto multiple lines — which means we'd need to add a `// @ts-ignore` for each of the 69 lines in the constructor. It looked like the `// @ts-ignore` was due to a small typing issue — `DataRow` appears to be the type for the values of the array, rather than the array. I refactored this in the first commit to allow me to remove the `// @ts-ignore`

### CODE REVIEW

**Comment by TangerineFloof** [comment]
We can't keep them 100% as-is and take Prettier. Prettier forces us to line-wrap the `return new Artisan`, and `// @ts-ignore` only applies to the immediately following line.

We would need to change it to:
```typescript
return new Artisan(
  // @ts-ignore
  data[0],
  // @ts-ignore
  data[1],
  // @ts-ignore
  data[2],
  ...
);
```
in order to match what was there.

We could instead change the type for `data` → `data: any`. This triggers an ESLint warning, but we can override it since we're already overriding a different ESLint warning to use `// @ts-ignore`. That would be the smallest total change/minimal conflicts with your branch.

**Comment by veelkoov** [comment]
How about adding the vue directory and single ts file to the ignore file?

**Comment by TangerineFloof** [comment]
We could do that if you really want to, but that would mean over half of the asset files (39/69) aren't being formatted.
 
If the concern is solely powered by concern around merge conflicts, I'd be happy to help on addressing those/rebasing the HTMX branch to resolve any merge conflicts caused by this PR.

**Comment by TangerineFloof** [comment]
Actually, for merge conflicts, I think you'd be able to take your changes 100% — that is, when you get merge conflicts, you ignore my changes entirely.

If your branch is removing all of the Vue files, those files will likely be deleted already. And it sounds like you've changed **Artisan.ts** and all of that enough that your branch has the "more recent" version so you can ignore the rework I'm doing here.

I think you'd be able to resolve all merge conflicts by taking your version, and then running `yarn prettier --write .` within the **symfony/** directory.

**Review by veelkoov — APPROVED** [review]

**Comment by veelkoov** [comment]
Thank you! :people_hugging:

**Pull request merged**
