### PR TITLE
Suggestion of T-Regx usage

### PR DESCRIPTION
**Pull request by danon**
1. You don't need to store `$i` counter variable, because you can use `$match->index()` method - it returns the ordinal number of the matched occurrence
2. `Matcher` is perfectly suitable to be used in `foreach`, it saves you from passing closed over variables as `&$ref`.

Let me know if you like the changes

### CODE REVIEW

**Comment by veelkoov** [comment]
@Danon thank you, these are helpful.

While testing I noticed PHPStan complaining about the foreach loop. Have you considered adding PHPStan support to T-Regx? Out of curiosity I did this: https://github.com/veelkoov/T-Regx-PHPStan/pull/1 . This is an absolute sketch/demo, without consulting the contribution rules, etc.

I don't know if you used PHPStan earlier; I highly recommend it. Dealing with it is sometimes cumbersome, but I found it very helpful. I'm not sure how much would it help you, I saw your tests are very rich and blazingly fast, but I thought you may consider; especially due to the fact, that library users could benefit from the support.

Also, I saw some Psalm annotations (at least "pure" functions). Do you maybe have some plans with that?

**Comment by veelkoov** [comment]
Disclaimer: I'm not an expert in PHPStan.

**Comment by Danon** [comment]
As yourself, I'm not an expert in phpstan or pslam at all, I didn't use such tools before. Like you noticed, I myself rely on Php types, tests and phpDoc annotations support from IDE. 

But I absolutely agree, that phpstan and psalm are useful tools, and many users might find them very helpful - and lack thereof might actually be a deal breaker.

The present annotations in the library were added by @iquito in https://github.com/t-regx/T-Regx/pull/77 I'm sure eventually a more concise and reliable way to add phpstan and psalm to the library is due, perhaps by someone who knows and uses these tools - as I said, I'm not an expert. However I'm more than open to add these annotations.

@veelkoov Feel free to open the Pull Request directly in https://github.com/t-regx/T-Regx and we'll continue the discussion there, if you'd like.

As of my plans, I'm currently writing documentations regarding this: https://github.com/t-regx/T-Regx/issues/17 to add detailed documentation to every public method, and with that I actually was planning to add proper phpstan annotations. Many reviewers consider documentation in public methods as a must-have for T-Regx `1.0`.

**Comment by veelkoov** [comment]
Opened as suggested

**Comment by Danon** [comment]
Link to PR: https://github.com/t-regx/T-Regx/pull/161

**Comment by veelkoov** [comment]
Thank you for your contribution. During the last few months I did a kind of experiment, which resulted with a lot of the code going away. Either way I appreciate your efforts of making maintaining PHP projects easier.

**Comment by veelkoov** [comment]
Merged within #198

**Pull request closed without merging**
