### PR TITLE
Suggestion of usage of another library

### PR DESCRIPTION
**Pull request by danon**
About 5 years ago, I created a library for data providers, then about 4 years ago I released version 2.0; it was horrible. For 4 years the library was used, and refined. In january I started the revamp of the library, and finished it few days ago - it's realeased as `3.1.0` now.

Maybe it looks good to you? https://github.com/t-regx/phpunit-data-provider

If you'd like it, feel free to use it; if you decided you don't need another dependency that's fine too! :) Just a friendly PR.

### CODE REVIEW

**Comment by veelkoov** [comment]
The autonaming feature is amazing.
When there are duplicates, it may be better to reference "global" index (in the test data) instead of duplicate index.

**Comment by danon** [comment]
> When there are duplicates, it may be better to reference "global" index (in the test data) instead of duplicate index.

@veelkoov I don't exactly understand what you mean by "global index". Do you have a particular test in mind in fuzzrake that could illustrate it?

**Comment by danon** [comment]
@veelkoov Thanks for the suggestion. Check out https://github.com/t-regx/phpunit-data-provider/releases/tag/3.2.0

**Comment by veelkoov** [comment]
image
Cool! Thank you

**Pull request closed without merging**
